// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using DotnetCore_TAS_CandidateAPI.Models;

namespace TAS_AngularCoreProj.Migrations
{
    [DbContext(typeof(CandidateProcessDBContext))]
    [Migration("20200515072433_updatecareer_150520")]
    partial class updatecareer_150520
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ApprovalLevel", b =>
                {
                    b.Property<int>("ApprovalLevelPKID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ApprovalLevels")
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(4000)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<bool?>("IsActive")
                        .HasColumnName("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnName("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("RoleFKID")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("varchar(4000)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime");

                    b.HasKey("ApprovalLevelPKID");

                    b.ToTable("ApprovalLevels");
                });

            modelBuilder.Entity("AssessmentQuestion", b =>
                {
                    b.Property<int>("AssessmentQuesPKID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(4000)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<bool?>("IsActive")
                        .HasColumnName("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnName("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Questions")
                        .HasColumnType("varchar(4000)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("varchar(4000)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime");

                    b.HasKey("AssessmentQuesPKID");

                    b.ToTable("AssessmentQuestions");
                });

            modelBuilder.Entity("City", b =>
                {
                    b.Property<int>("CityPKID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CityName")
                        .HasColumnType("varchar(4000)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(4000)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<bool?>("IsActive")
                        .HasColumnName("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnName("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("varchar(4000)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime");

                    b.HasKey("CityPKID");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("Department", b =>
                {
                    b.Property<int>("DepartmentPKID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(4000)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("DepartmentName")
                        .HasColumnType("varchar(4000)");

                    b.Property<bool?>("IsActive")
                        .HasColumnName("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnName("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("varchar(4000)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime");

                    b.HasKey("DepartmentPKID");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("Designation", b =>
                {
                    b.Property<int>("DesignationPKID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(4000)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("DesignationName")
                        .HasColumnType("varchar(4000)");

                    b.Property<bool?>("IsActive")
                        .HasColumnName("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnName("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("varchar(4000)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime");

                    b.HasKey("DesignationPKID");

                    b.ToTable("Designations");
                });

            modelBuilder.Entity("EducQualification", b =>
                {
                    b.Property<int>("QualificationPKID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(4000)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<bool?>("IsActive")
                        .HasColumnName("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnName("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Qualification")
                        .HasColumnType("varchar(4000)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("varchar(4000)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime");

                    b.HasKey("QualificationPKID");

                    b.ToTable("EducQualifications");
                });

            modelBuilder.Entity("EmailNotification", b =>
                {
                    b.Property<int>("EmailPKID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(4000)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("MailingDate")
                        .HasColumnType("datetime");

                    b.Property<string>("MessageBody")
                        .HasColumnType("varchar(4000)");

                    b.Property<string>("Recepients")
                        .HasColumnType("varchar(4000)");

                    b.Property<string>("SenderEmail")
                        .HasColumnType("varchar(4000)");

                    b.Property<string>("Subject")
                        .HasColumnType("varchar(4000)");

                    b.HasKey("EmailPKID");

                    b.ToTable("EmailNotifications");
                });

            modelBuilder.Entity("EmploymentType", b =>
                {
                    b.Property<int>("EmploymentTypePKID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(4000)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("EmploymentTypeName")
                        .HasColumnType("varchar(4000)");

                    b.Property<bool?>("IsActive")
                        .HasColumnName("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnName("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("varchar(4000)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime");

                    b.HasKey("EmploymentTypePKID");

                    b.ToTable("EmploymentTypes");
                });

            modelBuilder.Entity("Interview", b =>
                {
                    b.Property<int>("InterviewPKID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AssignedTo")
                        .HasColumnType("int");

                    b.Property<int>("CandidateFKID")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(4000)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("End_Time")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("InterviewDate")
                        .HasColumnType("datetime");

                    b.Property<int>("InterviewScheduledBy")
                        .HasColumnType("int");

                    b.Property<bool?>("IsActive")
                        .HasColumnName("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnName("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Remarks")
                        .HasColumnType("varchar(4000)");

                    b.Property<DateTime>("Start_Time")
                        .HasColumnType("datetime");

                    b.Property<int>("StatusFKID")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("varchar(4000)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime");

                    b.HasKey("InterviewPKID");

                    b.ToTable("Interviews");
                });

            modelBuilder.Entity("InterviewAssessment", b =>
                {
                    b.Property<int>("InterviewAssessPKID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AssessedBy")
                        .HasColumnType("int");

                    b.Property<int>("AssessmentQuesFKID")
                        .HasColumnType("int");

                    b.Property<int>("CandidateFKID")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(4000)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<int>("InterviewFKID")
                        .HasColumnType("int");

                    b.Property<int>("InterviewLevelFKID")
                        .HasColumnType("int");

                    b.Property<bool?>("IsActive")
                        .HasColumnName("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnName("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Ratings")
                        .HasColumnType("int");

                    b.Property<string>("Remarks")
                        .HasColumnType("varchar(4000)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("varchar(4000)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime");

                    b.HasKey("InterviewAssessPKID");

                    b.ToTable("InterviewAssessments");
                });

            modelBuilder.Entity("InterviewLevel", b =>
                {
                    b.Property<int>("InterviewLevelPKID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(4000)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("InterviewLevelType")
                        .HasColumnType("varchar(4000)");

                    b.Property<bool?>("IsActive")
                        .HasColumnName("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnName("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LevelNumber")
                        .HasColumnType("varchar(4000)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("varchar(4000)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime");

                    b.HasKey("InterviewLevelPKID");

                    b.ToTable("InterviewLevels");
                });

            modelBuilder.Entity("InterviewResult", b =>
                {
                    b.Property<int>("InterviewResultsPKID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ApprovedBy")
                        .HasColumnType("int");

                    b.Property<int>("AttendedRounds")
                        .HasColumnType("int");

                    b.Property<int>("CandidateFKID")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(4000)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<int>("InterviewFKID")
                        .HasColumnType("int");

                    b.Property<bool?>("IsActive")
                        .HasColumnName("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnName("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("JobPosterID")
                        .HasColumnType("varchar(4000)");

                    b.Property<string>("Remarks")
                        .HasColumnType("varchar(4000)");

                    b.Property<int>("StatusFKID")
                        .HasColumnType("int");

                    b.Property<int>("TotalRatings")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("varchar(4000)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime");

                    b.HasKey("InterviewResultsPKID");

                    b.ToTable("InterviewResults");
                });

            modelBuilder.Entity("JobLevel", b =>
                {
                    b.Property<int>("JobLevelPKID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(4000)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<bool?>("IsActive")
                        .HasColumnName("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnName("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("JobLevelName")
                        .HasColumnType("varchar(4000)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("varchar(4000)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime");

                    b.HasKey("JobLevelPKID");

                    b.ToTable("JobLevels");
                });

            modelBuilder.Entity("JobTitle", b =>
                {
                    b.Property<int>("JobTitlePKID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(4000)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<bool?>("IsActive")
                        .HasColumnName("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnName("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("JobTitleName")
                        .HasColumnType("varchar(4000)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("varchar(4000)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime");

                    b.HasKey("JobTitlePKID");

                    b.ToTable("JobTitles");
                });

            modelBuilder.Entity("Location", b =>
                {
                    b.Property<int>("LocationPKID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(4000)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<bool?>("IsActive")
                        .HasColumnName("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnName("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LocationName")
                        .HasColumnType("varchar(4000)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("varchar(4000)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime");

                    b.HasKey("LocationPKID");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("Log", b =>
                {
                    b.Property<int>("LogsPKID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AccessType")
                        .HasColumnType("varchar(4000)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(4000)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(4000)");

                    b.Property<bool?>("IsActive")
                        .HasColumnName("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnName("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LogsName")
                        .HasColumnType("varchar(4000)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("varchar(4000)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime");

                    b.Property<int>("UserFKID")
                        .HasColumnType("int");

                    b.HasKey("LogsPKID");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("Notification", b =>
                {
                    b.Property<int>("NotificationPKID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(4000)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(4000)");

                    b.Property<bool?>("IsActive")
                        .HasColumnName("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnName("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Notification_Action")
                        .HasColumnType("varchar(4000)");

                    b.Property<int>("UserFKID")
                        .HasColumnType("int");

                    b.HasKey("NotificationPKID");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("Questionnaire", b =>
                {
                    b.Property<int>("QuestionnairePKID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(4000)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<bool?>("IsActive")
                        .HasColumnName("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnName("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("QuestionnaireName")
                        .HasColumnType("varchar(4000)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("varchar(4000)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime");

                    b.HasKey("QuestionnairePKID");

                    b.ToTable("Questionnaires");
                });

            modelBuilder.Entity("RecruitmentReason", b =>
                {
                    b.Property<int>("RecruitReasonPKID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(4000)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<bool?>("IsActive")
                        .HasColumnName("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnName("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("RecruitReason")
                        .HasColumnType("varchar(4000)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("varchar(4000)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime");

                    b.HasKey("RecruitReasonPKID");

                    b.ToTable("RecruitmentReasons");
                });

            modelBuilder.Entity("Role_Permission", b =>
                {
                    b.Property<int>("RolePermissionPKID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(4000)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<bool?>("IsActive")
                        .HasColumnName("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnName("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("PermissionFKID")
                        .HasColumnType("int");

                    b.Property<int>("RoleFKID")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("varchar(4000)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime");

                    b.HasKey("RolePermissionPKID");

                    b.ToTable("Role_Permissions");
                });

            modelBuilder.Entity("Shift", b =>
                {
                    b.Property<int>("ShiftPKID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(4000)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<bool?>("IsActive")
                        .HasColumnName("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnName("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ShiftType")
                        .HasColumnType("varchar(4000)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("varchar(4000)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime");

                    b.HasKey("ShiftPKID");

                    b.ToTable("Shifts");
                });

            modelBuilder.Entity("Skill", b =>
                {
                    b.Property<int>("SkillsPKID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(4000)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<bool?>("IsActive")
                        .HasColumnName("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnName("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("SkillsName")
                        .HasColumnType("varchar(4000)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("varchar(4000)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime");

                    b.HasKey("SkillsPKID");

                    b.ToTable("Skills");
                });

            modelBuilder.Entity("State", b =>
                {
                    b.Property<int>("StatePKID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(4000)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<bool?>("IsActive")
                        .HasColumnName("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnName("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("StateName")
                        .HasColumnType("varchar(4000)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("varchar(4000)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime");

                    b.HasKey("StatePKID");

                    b.ToTable("States");
                });

            modelBuilder.Entity("Status", b =>
                {
                    b.Property<int>("StatusPKID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(4000)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("FlagStatus")
                        .HasColumnType("varchar(1000)");

                    b.Property<bool?>("IsActive")
                        .HasColumnName("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnName("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("StatusName")
                        .HasColumnType("varchar(4000)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("varchar(4000)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime");

                    b.HasKey("StatusPKID");

                    b.ToTable("Statuses");
                });

            modelBuilder.Entity("TalentCareerUpload", b =>
                {
                    b.Property<int>("CandidatePKID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CandidateName")
                        .HasColumnType("varchar(4000)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(4000)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("CurrentCompany")
                        .HasColumnType("varchar(4000)");

                    b.Property<string>("CurrentLocation")
                        .HasColumnType("varchar(4000)");

                    b.Property<string>("Designation")
                        .HasColumnType("varchar(4000)");

                    b.Property<int?>("EducQualifyFKID")
                        .HasColumnType("int");

                    b.Property<string>("EmailID")
                        .HasColumnType("varchar(4000)");

                    b.Property<int?>("FuncSkillsFKID")
                        .HasColumnType("int");

                    b.Property<bool?>("IsActive")
                        .HasColumnName("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsApprove")
                        .HasColumnName("IsApprove")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsReject")
                        .HasColumnName("IsReject")
                        .HasColumnType("bit");

                    b.Property<string>("JobPosterID")
                        .HasColumnType("varchar(4000)");

                    b.Property<string>("JobReferenceNumber")
                        .HasColumnType("varchar(4000)");

                    b.Property<string>("MobileNumber")
                        .HasColumnType("varchar(4000)");

                    b.Property<int?>("PreferredLocationFKID")
                        .HasColumnType("int");

                    b.Property<string>("Resume")
                        .HasColumnType("varchar(4000)");

                    b.Property<int?>("TechSkillsFKID")
                        .HasColumnType("int");

                    b.Property<int?>("TotalExperience")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("varchar(4000)");

                    b.Property<DateTime?>("UploadedDate")
                        .HasColumnType("datetime");

                    b.HasKey("CandidatePKID");

                    b.ToTable("TalentCareerUploads");
                });

            modelBuilder.Entity("TalentRequest", b =>
                {
                    b.Property<int>("JobRequisitionPKID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AdditionalNotes")
                        .HasColumnType("varchar(4000)");

                    b.Property<string>("ApprovedBy")
                        .HasColumnType("varchar(4000)");

                    b.Property<string>("ApproverFKID")
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int>("CityFKID")
                        .HasColumnType("int");

                    b.Property<string>("CollaboratorFKID")
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(4000)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("DepartmentFKID")
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(4000)");

                    b.Property<int?>("DurationFKID")
                        .HasColumnType("int");

                    b.Property<string>("EmpcumDurationtext")
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int>("EmploymentTypeFKID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime");

                    b.Property<string>("GoodSkillsFKID")
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("InterviewLevelFKID")
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int>("InterviewRounds")
                        .HasColumnType("int");

                    b.Property<bool?>("IsActive")
                        .HasColumnName("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsApprove")
                        .HasColumnName("IsApprove")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsReject")
                        .HasColumnName("IsReject")
                        .HasColumnType("bit");

                    b.Property<string>("JobLevelFKID")
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int>("JobOpeningsCount")
                        .HasColumnType("int");

                    b.Property<string>("JobPosterID")
                        .HasColumnType("varchar(4000)");

                    b.Property<string>("JobTitleFKID")
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int>("LocationFKID")
                        .HasColumnType("int");

                    b.Property<string>("MandSkillsFKID")
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("NextApproverLevel")
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("OverallExperience")
                        .HasColumnType("int");

                    b.Property<string>("QuestionnaireFKID")
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("RecruitReasonFKID")
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int>("Salary")
                        .HasColumnType("int");

                    b.Property<string>("ShiftFKID")
                        .HasColumnType("nvarchar(4000)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime");

                    b.Property<int>("StateFKID")
                        .HasColumnType("int");

                    b.Property<string>("StatusFKID")
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("TaskFKID")
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("TravelFKID")
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("varchar(4000)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime");

                    b.HasKey("JobRequisitionPKID");

                    b.ToTable("TalentRequests");
                });

            modelBuilder.Entity("TalentRequest_SaveDraft", b =>
                {
                    b.Property<int>("JobRequisitionPKID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AdditionalNotes")
                        .HasColumnType("varchar(4000)");

                    b.Property<string>("ApprovedBy")
                        .HasColumnType("varchar(4000)");

                    b.Property<string>("ApproverFKID")
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int?>("CityFKID")
                        .HasColumnType("int");

                    b.Property<string>("CollaboratorFKID")
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(4000)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("DepartmentFKID")
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(4000)");

                    b.Property<int?>("DurationFKID")
                        .HasColumnType("int");

                    b.Property<int?>("EmploymentTypeFKID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime");

                    b.Property<string>("GoodSkillsFKID")
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("InterviewLevelFKID")
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int?>("InterviewRounds")
                        .HasColumnType("int");

                    b.Property<bool?>("IsActive")
                        .HasColumnName("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsApprove")
                        .HasColumnName("IsApprove")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsReject")
                        .HasColumnName("IsReject")
                        .HasColumnType("bit");

                    b.Property<string>("JobLevelFKID")
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int?>("JobOpeningsCount")
                        .HasColumnType("int");

                    b.Property<string>("JobPosterID")
                        .HasColumnType("varchar(4000)");

                    b.Property<string>("JobTitleFKID")
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int?>("LocationFKID")
                        .HasColumnType("int");

                    b.Property<string>("MandSkillsFKID")
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int?>("OverallExperience")
                        .HasColumnType("int");

                    b.Property<string>("QuestionnaireFKID")
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("RecruitReasonFKID")
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int?>("Salary")
                        .HasColumnType("int");

                    b.Property<string>("ShiftFKID")
                        .HasColumnType("nvarchar(4000)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime");

                    b.Property<int?>("StateFKID")
                        .HasColumnType("int");

                    b.Property<string>("StatusFKID")
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int?>("TaskFKID")
                        .HasColumnType("int");

                    b.Property<string>("TravelFKID")
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("varchar(4000)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("ViewStatus")
                        .HasColumnType("varchar(200)");

                    b.HasKey("JobRequisitionPKID");

                    b.ToTable("TalentRequest_SaveDrafts");
                });

            modelBuilder.Entity("Task", b =>
                {
                    b.Property<int>("TasksPKID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ActionUserID")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(4000)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(4000)");

                    b.Property<bool?>("IsActive")
                        .HasColumnName("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsApproved")
                        .HasColumnName("IsApproved")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsCompleted")
                        .HasColumnName("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnName("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsOnhold")
                        .HasColumnName("IsOnhold")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsRejected")
                        .HasColumnName("IsRejected")
                        .HasColumnType("bit");

                    b.Property<string>("JobPosterID")
                        .HasColumnType("varchar(4000)");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("TasksActivity")
                        .HasColumnType("varchar(4000)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("varchar(4000)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime");

                    b.HasKey("TasksPKID");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("Travel", b =>
                {
                    b.Property<int>("TravelPKID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(4000)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<bool?>("IsActive")
                        .HasColumnName("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnName("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("TravelType")
                        .HasColumnType("varchar(4000)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("varchar(4000)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime");

                    b.HasKey("TravelPKID");

                    b.ToTable("Travels");
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Property<int>("UserPKID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("varchar(4000)");

                    b.Property<int>("CityFKID")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(4000)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DOJ")
                        .HasColumnType("datetime");

                    b.Property<string>("EmployeeID")
                        .HasColumnType("varchar(4000)");

                    b.Property<bool?>("IsActive")
                        .HasColumnName("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnName("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsRemember")
                        .HasColumnName("IsRemember")
                        .HasColumnType("bit");

                    b.Property<string>("Mobile")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NewPassword")
                        .HasColumnType("varchar(4000)");

                    b.Property<string>("OldPassword")
                        .HasColumnType("varchar(4000)");

                    b.Property<int>("PinCode")
                        .HasColumnType("int");

                    b.Property<string>("ProfileImage")
                        .HasColumnType("varchar(4000)");

                    b.Property<int>("RoleFKID")
                        .HasColumnType("int");

                    b.Property<int>("StateFKID")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("varchar(4000)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("UserEmail")
                        .HasColumnType("varchar(4000)");

                    b.Property<string>("UserName")
                        .HasColumnType("varchar(4000)");

                    b.HasKey("UserPKID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("UserPermission", b =>
                {
                    b.Property<int>("PermissionPKID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(4000)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(4000)");

                    b.Property<bool?>("IsActive")
                        .HasColumnName("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnName("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("PermissionTitle")
                        .HasColumnType("varchar(4000)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("varchar(4000)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime");

                    b.HasKey("PermissionPKID");

                    b.ToTable("UserPermissions");
                });

            modelBuilder.Entity("UserRole", b =>
                {
                    b.Property<int>("RolePKID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(4000)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<bool?>("IsActive")
                        .HasColumnName("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnName("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("RoleTitle")
                        .HasColumnType("varchar(4000)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("varchar(4000)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime");

                    b.HasKey("RolePKID");

                    b.ToTable("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
